### ISSUE TITLE
Linux install

### ISSUE THREAD

**Issue by iandoug** [binarybottle/engram#11]
Hi Arno

Does that approach work for Linux? Thought you normally needed to edit assorted xkb config files as well?

I've had too much fun and games trying to add my own layouts ... eventually just edited the Colemak section and used that.

One problem with your approach is that system updates may overwrite the us file... I think the "proper" approach is via something like how EUKeys does it, but I couldn't get that to work either ...

Cheers, Ian

**Comment by caga** [comment]
Hi ian,

> Does that approach work for Linux? Thought you normally needed to edit assorted xkb config files as well?

i also have not fancy current linux installation method but it will be ok for most of the people for now i suppose. 

You are right about that you have to dive into xkb configuration but it is not easy if you try to do something fancy like for example
pressing alt+l gives you return or alt+r backspace and like multiple modifiers groupings and layering ... But probabilities is endless if you learn xkb configuration well. even maybe more powerful than having a programmable keyboard (qmk firmware...).

i have made a us variant of old engram layout on linux with extra cool stuff, using it right now. 

i had a plan of writing a script for people who want to install xkb way, so i would contribute the project that way but layout has been optimised and changed recently multible times.  if i have time i will prepare a linux layout soon. 

but before that i am planning to prepare a qmk engram layout , so any people with qmk compatible keyboard may use the layout on any computer or on any OS once flashed it to their keyboard.

Cheers, cagatay

**Comment by sunaku** [comment]
@iandoug This particular approach of appending to the US file definitely works: I've been using it successfully to apply [a different layout](https://github.com/sunaku/beakl15p) for the last 6 months.  You're right that it's not permanent: system updates to XKB sometimes revert the appended snippet, in which case I've had to manually append it again.  The good news is that we can at least automate installation (as well as uninstallation) through a simple Makefile - I'll submit a PR for that sometime this weekend. :star_struck:

**Comment by iandoug** [comment]
> PS: i just looked at your github and see that you are the author of http://www.keyboard-layout-editor.com . So i salute you with deep respect

No, that's Ian Prest, though I did contribute some things.

**Comment by binarybottle** [comment]
> i have made a us variant of old engram layout on linux with extra cool stuff, using it right now.
@caga -- Thank you.  Note that version 2 (the one on the website and keyman) should be the only one we pursue to reduce confusion.

**Comment by caga** [comment]
@binarybottle 
Please don't worry. i will pursue the v2 :)
i am about to begin preparing two "qmk" general keycodes headers for engram layout. We need this because as shifted characters are different than standart us layout. 

i was infact thinking working with unicode charchacters (so engram loaded keyboard will behave same, free from OS and any preset layout  as most OS has ibus for unicode chars) then i thought it will be too much eccentric. i should follow the standart way, at least in the begining.

After i finish headers and also a (slightly modified) layout for my planck and see everything works well, i will inform you :) and then we should make a pull request from qmk for other keyboard enthusiasts to use engram. :)

Let's make Engram Great Again! :sweat_smile:  

(Ps: no political tendency, just like the phrase) :hugs:

**Comment by binarybottle** [comment]
Thank you, @caga!

**Comment by sunaku** [comment]
I think this issue can be closed now, since PR #12 has been merged.
