### ISSUE TITLE
Programming version

### ISSUE THREAD

**Issue by WizardMaggot** [binarybottle/engram#26]
It would be cool to have the symbols already readily available before holding shift. The curly brace locations are also not really nice far the pinkies. Maybe have the algorithm analyze some popular open source programs? 

Thanks!

**Comment by binarybottle** [comment]
In "programmer" variants of popular layouts (like Programmer Dvorak), the numbers and symbols are swapped, so you have to press Shift to access the number keys.  I didn't want to do that, as numbers are more frequently used more broadly.

In https://github.com/binarybottle/engram#summary I referred to:
"Computer Languages Character Frequency" by Xah Lee.
http://xahlee.info/comp/computer_language_char_distribution.html

Curly braces are generally rather infrequent, which is why I pushed them to the sides.

**Comment by WizardMaggot** [comment]
You have a great point, that would be very optimal for normal usage. But what about the brackets? Since they are used more, would they be more efficient if they were put in between 5 and 6? 
I suppose it shouldn't add much of a learning curve while still retaining their usage. The brackets and curly braces which are less used should just be accessible through shift based on the data in your links. (although typing 0 and 1 might be a little more difficult unless you shift your hands around). 

Thanks for your time!

**Comment by binarybottle** [comment]
Thank you very much for your suggestions, as it is always fun to think about different possible variations. However, I do wish to keep the numbers in their numerical order without gaps. You are welcome to try different number and punctuation sequences.

**Comment by WizardMaggot** [comment]
Okay, I'll experiment with it

**Comment by binarybottle** [comment]
Great, thanks, @WizardMaggot  -- Please feel free to continue this thread in the Discussions (https://github.com/binarybottle/engram/discussions).  In the meantime, I will close this issue.
