### ISSUE TITLE
Mirror left and right layouts?

### ISSUE THREAD

**Issue by franticnerd** [binarybottle/engram#42]
First of all, thanks for making this great layout, I really love it! I've been using it for one month and it's very comfortable.

In the current Engram 2.0 design, the vowel letters are on the left, and the most frequent consonants the on the right. I am thinking about mirroring the left and right layouts, to put the consonants on left and vowels on the right. Something like:
z v w d l ' " u o y b
q n s t h , . a e i c
 _ p f m r - ? k j x g

Below is my motivation:

When we speak and write English, we often go from left to right. Most English words start with consonants letters (such as s h d m t). Plus, many people typically type on a syllable basis, and the beginning of each syllable is more often to be consonants rather than vowels. As a result. When I type using the Engram 2.0 layout, I often have to go with the reverse direction: start from the right hand and go to my left, which is a little bit unnatural. What if we mirror the left and right layouts?

I checked the Engram paper to understand the design philosophy, but I did not find too much justification of putting the vowels on the left instead of on the right. The only reason I could come up with is probably some bigrams like IE EA can be typed from left to right. But the same justification can be also applied if we mirror the left and right layout, which means some consonants like ST TH can go from left to right after mirroring. 

@binarybottle , what's your thoughts on this idea?

**Comment by binarybottle** [comment]
Thank you for your excellent question, @franticnerd!

I had given consideration to a mirror version of the layout for the reason you mention above, but did not, because in traditional keyboard designs there are two more keys on the right side.  If you place the least frequent letters in English (Z and Q) where these two keys are, then the optimized bigram rolls result in the vowels on the left side in all my tests.

**Comment by franticnerd** [comment]
Thanks @binarybottle for the insight!

Regarding that issue, using tools like kmonad (https://github.com/kmonad/kmonad), I can remap the "tab" key to "z", and the "caps lock" key to "q", which will still preserve inward rolls for both hands.  In that case, are there any other reasons not to use to the mirrored version?

**Comment by binarybottle** [comment]
None that I can think of!

**Comment by franticnerd** [comment]
Thanks @binarybottle !

**Comment by masters3d** [comment]
I have also considered mirroring the layouts ( assuming I can put the q and z lower middle section or number row at 5 and 6 ).

**Comment by sunaku** [comment]
I have sometimes wondered whether placing the vowels on the right hand would better serve me since I'm right-handed (and thus shift the vowel load onto my main hand), but alas the same rationale also supports keeping the vowels on the left: I start sentences with my right hand (due to handedness) anyway, so the standard Engram 2.0 layout also feels quite natural to me. :man_shrugging:  Or perhaps it's because of my long history with having all the vowels on the left hand, coming from 16 years of using Dvorak. :older_man:

**Comment by masters3d** [comment]
I tried the mirrored version for a couple of weeks and the placement of IC did not sit well with me. Perhaps because coming from querty the placement for `IC` is `L;` vs on the regular orientation `CI` maps to querty `AS` which is used a lot more often so the neural pathways for CI left hand motion are stronger than right handed IC motion. 

At any rate I think it's doable but the extra keys have to go in the middle column which defeats the purpose in a way. 

After some time I decided to adopt a layout that is closer to https://keyboard-design.com/letterlayout.html?layout=full-maks.en.ergodox

I still like the vowel grid which mirrors perfectly in both layouts. 
```
you   uoy
iea   aei
```
